name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    name: Install
    runs-on: ubuntu-latest
    outputs:
      pnpm_store: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

  test-bot:
    name: Bot unit tests (Vitest)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/bot test

  test-web:
    name: Web E2E (Playwright)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm --filter ./apps/web exec playwright install --with-deps

      # Your web tests already start a server via Playwright config / test script.
      - name: Run Playwright tests (snapshots)
        run: pnpm --filter ./apps/web run test:snapshots

      - name: Upload Playwright report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report/
