name: Web E2E

on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'configs/tokens/**'
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'configs/tokens/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers (web app only)
        run: pnpm --filter ./apps/web exec playwright install --with-deps

      # Runs in CI mode (Playwright starts Next dev server via webServer in playwright.config.ts)
      - name: Run E2E
        run: pnpm --filter ./apps/web run e2e:ci
        env:
          CI: 'true'

      - name: Upload Playwright report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report